// Generated by CoffeeScript 1.8.0
(function() {
  describe("JetPack.js Unit Test Library", function() {});

  it("test 1", function(cb) {
    var jp;
    jp = new JetPack();
    expect(jp.getVersion()).to.equal('JetPack v 1.0');
    expect(jp.toString()).to.equal('');
    return cb();
  });

}).call(this);
