// Generated by CoffeeScript 1.8.0
(function() {
  this.JetPack = (function() {
    function JetPack() {}

    JetPack.prototype.getVersion = function(meters) {
      return "JetPack v 1.0";
    };

    JetPack.prototype.toString = function() {
      return "";
    };

    return JetPack;

  })();

}).call(this);
